kramdown:
  input: Kramdown

title: "Leonardo Tanzi"
author: "Leonardo Tanzi"
description: "Leonardo Tanzi's Website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.md"}
  - {title: "Projects", file: "blog.md", icon: cubes}
  - {url: "https://leonardotanzi.github.io/Full_CV_Leonardo_Tanzi.pdf", class="ext-link", title: "CV", icon: file-code}
  - {title: "Methinks AI", url: "https://www.methinks.ai/", icon: brain}
  - {title: "Medium", url: "https://medium.com/@leonardo.tanzi", icon: bars}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:leonardo.tanzi@polito.it"}
  - {title: Github, icon: github, url: "https://github.com/leonardotanzi"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/leonardo-tanzi/"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Leonardo-Tanzi"}
  - {title: Scholar, icon: book-open, url: "https://scholar.google.com/citations?user=s0p13UEAAAAJ&hl=it"}
  - {title: GANs, icon: instagram, url: "https://www.instagram.com/intingol1/"}
  - {title: Chess, icon: chess, url: "https://lichess.org/@/leobrang"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
