title: "Leonardo Tanzi"
author: "Leonardo Tanzi"
description: "Polytechnic University of Turin"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://leonardotanzi.github.io/Full_CV_Leonardo_Tanzi.pdf", title: "CV"}
  - {title: "Lab", url: "https://www.3dlab.polito.it"}
  - {title: "Blog", url: "https://medium.com/@leonardo.tanzi"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:leonardo.tanzi@polito.it"}
  - {title: Github, icon: github, url: "https://github.com/leonardotanzi"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/leonardo-tanzi/"}
  - {title: IG, icon: instagram, url: "https://www.instagram.com/intingol1/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
